apply plugin: 'com.android.application'
apply plugin: 'org.greenrobot.greendao'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'


android {
    compileSdkVersion 29
    defaultConfig {
        applicationId "com.nnmedia.novel"
        minSdkVersion 23
        targetSdkVersion 28
        versionCode 46
        versionName "1.3.8"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        multiDexEnabled true

        // 添加一个默认渠道号
//        manifestPlaceholders = [UMENG_CHANNEL_VALUE: "Umeng"]
        flavorDimensions "versionCode"

        ndk {
            abiFilters "armeabi-v7a"
            abiFilters 'armeabi'
            abiFilters 'arm64-v8a'
        }

        javaCompileOptions {
            //告知RxHttp你依赖的okhttp版本，目前已适配 v3.12.0 - v4.7.2版本
            annotationProcessorOptions {
                arguments = [
                        rxhttp_okhttp : '4.7.2',
                        rxhttp_rxjava : 'rxjava3', //告知RxHttp你依赖的rxjava版本，可传入rxjava2、rxjava3
                        rxhttp_package: 'com.nnmedia.novel'   //指定RxHttp相关类的生成路径，即包名
                ]
            }
        }
        compileOptions {
            encoding = 'UTF-8'
            sourceCompatibility JavaVersion.VERSION_1_8
            targetCompatibility JavaVersion.VERSION_1_8
        }
    }

    signingConfigs {
        // debug 使用系统默认的 debug keystore
        // debug {
        //     storeFile file("C:/Users/hp/.android/debug.keystore")
        // }
        // release 签名配置
        release {
            storeFile file("../doc/book_keystore.jks")
            storePassword "book1688"
            keyAlias "book"
            keyPassword "book1688"
        }
    }

    //Caused by: org.gradle.api.GradleException: Lint found fatal errors while assembling a release target.
    //添加如下配置
    lintOptions {
        checkReleaseBuilds false
        abortOnError false
    }

    buildTypes {
        debug {
            buildConfigField "boolean", "LOG_DEBUG", "true"
            versionNameSuffix "-debug"
            zipAlignEnabled false
            shrinkResources false
            minifyEnabled false
//            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
        release {
            // 不显示Log
            buildConfigField "boolean", "LOG_DEBUG", "false"
            //混淆
            minifyEnabled true
            //false
            zipAlignEnabled true
            // 移除无用的resource文件，shrinkResources依赖于minifyEnabled,必须一起用
            shrinkResources true
            //前一部分代表系统默认的android程序的混淆文件，该文件已经包含了基本的混淆声明，后一个文件是自己的定义混淆文件
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            //签名
            signingConfig signingConfigs.release

            applicationVariants.all { variant ->
                variant.outputs.all { output ->
                    //定义apk名字
                    def formatedTime = new Date().format("yyyy-MM-dd")
                    def apkFileName = "novel_app_v${android.defaultConfig.versionName}_${formatedTime}.apk"
                    outputFileName = apkFileName
                }
            }
        }
    }

    //多渠道打包支持
    productFlavors {
        Invite {}//自己的邀请链接下载
    }
    //manifestPlaceholders 使用相关的值替换了UMENG_CHANNEL_VALUE
    productFlavors.all {
        flavor -> flavor.manifestPlaceholders = [UMENG_CHANNEL_VALUE: name]
    }

    sourceSets {
        main {
            jniLibs.srcDirs = ['libs']
        }
    }

}

greendao {
    schemaVersion 1
    daoPackage 'com.nnmedia.page.model.dao'
    targetGenDir 'src/main/java'
}

repositories {
    maven {
        url 'https://dl.bintray.com/qichuan/maven/'
    }
    flatDir {
        dirs 'libs'
    }
}

dependencies {
    implementation fileTree(include: ['*.aar', '*.jar'], exclude: [], dir: 'libs')
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
    testImplementation 'junit:junit:4.13'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'

    implementation 'com.google.android.material:material:1.1.0'
    implementation 'androidx.multidex:multidex:2.0.1'

    //bugly
    implementation 'com.tencent.bugly:crashreport:latest.release'
    //appsflyer
    implementation 'com.appsflyer:af-android-sdk:6.12.1'
    //友盟
    implementation  'com.umeng.umsdk:common:9.4.7'// 必选
    implementation  'com.umeng.umsdk:asms:1.4.0'// 必选

    //RxHttp
    implementation 'com.ljx.rxlife:rxlife-coroutine:2.0.0' //管理协程生命周期，页面销毁，关闭请求
    implementation 'com.ljx.rxhttp:rxhttp:2.2.8'
    annotationProcessor 'com.ljx.rxhttp:rxhttp-compiler:2.2.8'
    //生成RxHttp类，非kotlin项目，请使用annotationProcessor代替kapt
    implementation 'com.squareup.okhttp3:okhttp:4.7.2' //rxhttp v2.2.2版本起，需要手动依赖okhttp

    //rxjava3
    implementation 'io.reactivex.rxjava3:rxjava:3.0.2'
    implementation 'io.reactivex.rxjava3:rxandroid:3.0.0'
    implementation 'com.ljx.rxlife3:rxlife-rxjava:3.0.0' //管理RxJava3生命周期，页面销毁，关闭请求

    implementation 'io.reactivex:rxjava:1.3.8'
    implementation 'io.reactivex:rxandroid:1.2.1'

    implementation 'com.google.code.gson:gson:2.8.6'
    //Converter 根据自己需求选择 RxHttp默认内置了GsonConverter
//    implementation 'com.ljx.rxhttp:converter-jackson:2.2.8'
    implementation 'com.ljx.rxhttp:converter-fastjson:2.2.8'
//    implementation 'com.ljx.rxhttp:converter-protobuf:2.2.8'
//    implementation 'com.ljx.rxhttp:converter-simplexml:2.2.8'
    //RxHttp

    implementation 'com.alibaba:fastjson:1.2.62'

    //glide
    implementation 'com.github.bumptech.glide:glide:4.11.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.11.0'

    //eventbus
    implementation 'org.greenrobot:eventbus:3.2.0'

    implementation 'com.kongzue.stacklabel:stacklabelview:1.1.9'
    implementation 'com.kongzue.dialog_v3x:dialog:3.1.9'

    implementation 'com.github.CymChad:BaseRecyclerViewAdapterHelper:3.0.4'

    implementation 'me.zhanghai.android.materialratingbar:library:1.4.0'

    //屏幕适配
    implementation 'me.jessyan:autosize:1.1.2'

    //下拉刷新上拉加载
    implementation 'com.scwang.smartrefresh:SmartRefreshLayout:1.1.0'
    implementation 'com.scwang.smartrefresh:SmartRefreshHeader:1.1.0'

    //    implementation "androidx.swiperefreshlayout:swiperefreshlayout:1.0.0"
    implementation 'pub.devrel:easypermissions:2.0.1'

    //轮播图
//    implementation 'com.youth.banner:banner:1.4.10'
    implementation 'io.github.youth5201314:banner:2.2.2'
    implementation project(path: ':stepview')
    implementation project(path: ':flycoTabLayout_lib')
    // OpenCC to convert Simp. Chinese to Trad. Chinese
    implementation 'com.zqc.opencc.android.lib:lib-opencc-android:0.8.0@aar'

    // ORM Database
    implementation 'org.greenrobot:greendao:3.2.2'

    //日志
    implementation 'com.orhanobut:logger:2.2.0'
    //注解
    implementation 'com.jakewharton:butterknife:10.2.1'
    annotationProcessor 'com.jakewharton:butterknife-compiler:10.2.1'
    //下划线
    implementation 'com.yqritc:recyclerview-flexibledivider:1.4.0'
    //动画
    implementation 'com.airbnb.android:lottie:3.0.7'

    //App升级
    implementation 'com.azhon:appupdateX:3.0.0'

    //js交互
//    implementation 'com.github.lzyzsd:jsbridge:1.0.4'

    //可拖拽徽章空间
    implementation 'cn.bingoogolapple:bga-badgeview-api:1.1.8'
    annotationProcessor "cn.bingoogolapple:bga-badgeview-compiler:1.1.8"

    //launcher角标
    implementation "me.leolin:ShortcutBadger:1.1.22@aar"

    //二维码
    implementation 'com.journeyapps:zxing-android-embedded:3.6.0'
    implementation 'com.google.zxing:core:3.3.2'

    //自定义seekbar
    implementation 'com.xw.repo:bubbleseekbar:3.20'

    implementation 'org.adw.library:discrete-seekbar:1.0.1'

    // Jsoup - HTML 解析库
    implementation 'org.jsoup:jsoup:1.16.1'

    // Rhino - JavaScript 引擎，用于解密 eval() 代码
    implementation 'org.mozilla:rhino:1.7.14'

    implementation 'com.facebook.fresco:fresco:2.3.0'

    //判断是否是模拟器
//    implementation 'io.github.happylishang:antifake:1.7.0'
//    implementation 'com.lahm.library:easy-protector-release:latest.release'

    //微信支付
//    implementation 'com.tencent.mm.opensdk:wechat-sdk-android-with-mta:5.4.0'
    //Alipay支付
//    implementation(name: 'alipaySdk-15.7.4-20200228192259', ext: 'aar')

//    implementation(name: 'CTAccountSdk_HY_v3.7.2_all', ext: 'aar')
//    implementation(name: 'ShareInstall_v1.2.6', ext: 'aar')
//    implementation(name: 'ShareInstallAutoLogin_v1.2.6', ext: 'aar')
//    implementation(name: 'open_ad_sdk', ext: 'aar')
}