package com.nnmedia.page.model.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.nnmedia.comics.model.Chapter;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CHAPTER".
*/
public class ChapterDao extends AbstractDao<Chapter, Long> {

    public static final String TABLENAME = "CHAPTER";

    /**
     * Properties of entity Chapter.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property SourceComic = new Property(1, Long.class, "sourceComic", false, "SOURCE_COMIC");
        public final static Property Title = new Property(2, String.class, "title", false, "TITLE");
        public final static Property Path = new Property(3, String.class, "path", false, "PATH");
        public final static Property Count = new Property(4, int.class, "count", false, "COUNT");
        public final static Property Complete = new Property(5, boolean.class, "complete", false, "COMPLETE");
        public final static Property Download = new Property(6, boolean.class, "download", false, "DOWNLOAD");
        public final static Property Tid = new Property(7, long.class, "tid", false, "TID");
        public final static Property SourceGroup = new Property(8, String.class, "sourceGroup", false, "SOURCE_GROUP");
    }


    public ChapterDao(DaoConfig config) {
        super(config);
    }
    
    public ChapterDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CHAPTER\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"SOURCE_COMIC\" INTEGER NOT NULL ," + // 1: sourceComic
                "\"TITLE\" TEXT," + // 2: title
                "\"PATH\" TEXT," + // 3: path
                "\"COUNT\" INTEGER NOT NULL ," + // 4: count
                "\"COMPLETE\" INTEGER NOT NULL ," + // 5: complete
                "\"DOWNLOAD\" INTEGER NOT NULL ," + // 6: download
                "\"TID\" INTEGER NOT NULL ," + // 7: tid
                "\"SOURCE_GROUP\" TEXT);"); // 8: sourceGroup
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CHAPTER\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Chapter entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getSourceComic());
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(3, title);
        }
 
        String path = entity.getPath();
        if (path != null) {
            stmt.bindString(4, path);
        }
        stmt.bindLong(5, entity.getCount());
        stmt.bindLong(6, entity.getComplete() ? 1L: 0L);
        stmt.bindLong(7, entity.getDownload() ? 1L: 0L);
        stmt.bindLong(8, entity.getTid());
 
        String sourceGroup = entity.getSourceGroup();
        if (sourceGroup != null) {
            stmt.bindString(9, sourceGroup);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Chapter entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getSourceComic());
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(3, title);
        }
 
        String path = entity.getPath();
        if (path != null) {
            stmt.bindString(4, path);
        }
        stmt.bindLong(5, entity.getCount());
        stmt.bindLong(6, entity.getComplete() ? 1L: 0L);
        stmt.bindLong(7, entity.getDownload() ? 1L: 0L);
        stmt.bindLong(8, entity.getTid());
 
        String sourceGroup = entity.getSourceGroup();
        if (sourceGroup != null) {
            stmt.bindString(9, sourceGroup);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Chapter readEntity(Cursor cursor, int offset) {
        Chapter entity = new Chapter( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // sourceComic
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // title
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // path
            cursor.getInt(offset + 4), // count
            cursor.getShort(offset + 5) != 0, // complete
            cursor.getShort(offset + 6) != 0, // download
            cursor.getLong(offset + 7), // tid
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8) // sourceGroup
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Chapter entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSourceComic(cursor.getLong(offset + 1));
        entity.setTitle(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setPath(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setCount(cursor.getInt(offset + 4));
        entity.setComplete(cursor.getShort(offset + 5) != 0);
        entity.setDownload(cursor.getShort(offset + 6) != 0);
        entity.setTid(cursor.getLong(offset + 7));
        entity.setSourceGroup(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Chapter entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Chapter entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Chapter entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
