package com.nnmedia.page.model.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.nnmedia.comics.model.Chapter;
import com.nnmedia.comics.model.Comic;
import com.nnmedia.comics.model.ImageUrl;
import com.nnmedia.comics.model.Source;
import com.nnmedia.comics.model.Tag;
import com.nnmedia.comics.model.TagRef;
import com.nnmedia.comics.model.Task;
import com.nnmedia.page.model.bean.BookChapter;
import com.nnmedia.page.model.bean.BookRecordBean;
import com.nnmedia.page.model.bean.ChapterBean;
import com.nnmedia.page.model.bean.DownloadTaskBean;

import com.nnmedia.page.model.dao.ChapterDao;
import com.nnmedia.page.model.dao.ComicDao;
import com.nnmedia.page.model.dao.ImageUrlDao;
import com.nnmedia.page.model.dao.SourceDao;
import com.nnmedia.page.model.dao.TagDao;
import com.nnmedia.page.model.dao.TagRefDao;
import com.nnmedia.page.model.dao.TaskDao;
import com.nnmedia.page.model.dao.BookChapterDao;
import com.nnmedia.page.model.dao.BookRecordBeanDao;
import com.nnmedia.page.model.dao.ChapterBeanDao;
import com.nnmedia.page.model.dao.DownloadTaskBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig chapterDaoConfig;
    private final DaoConfig comicDaoConfig;
    private final DaoConfig imageUrlDaoConfig;
    private final DaoConfig sourceDaoConfig;
    private final DaoConfig tagDaoConfig;
    private final DaoConfig tagRefDaoConfig;
    private final DaoConfig taskDaoConfig;
    private final DaoConfig bookChapterDaoConfig;
    private final DaoConfig bookRecordBeanDaoConfig;
    private final DaoConfig chapterBeanDaoConfig;
    private final DaoConfig downloadTaskBeanDaoConfig;

    private final ChapterDao chapterDao;
    private final ComicDao comicDao;
    private final ImageUrlDao imageUrlDao;
    private final SourceDao sourceDao;
    private final TagDao tagDao;
    private final TagRefDao tagRefDao;
    private final TaskDao taskDao;
    private final BookChapterDao bookChapterDao;
    private final BookRecordBeanDao bookRecordBeanDao;
    private final ChapterBeanDao chapterBeanDao;
    private final DownloadTaskBeanDao downloadTaskBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        chapterDaoConfig = daoConfigMap.get(ChapterDao.class).clone();
        chapterDaoConfig.initIdentityScope(type);

        comicDaoConfig = daoConfigMap.get(ComicDao.class).clone();
        comicDaoConfig.initIdentityScope(type);

        imageUrlDaoConfig = daoConfigMap.get(ImageUrlDao.class).clone();
        imageUrlDaoConfig.initIdentityScope(type);

        sourceDaoConfig = daoConfigMap.get(SourceDao.class).clone();
        sourceDaoConfig.initIdentityScope(type);

        tagDaoConfig = daoConfigMap.get(TagDao.class).clone();
        tagDaoConfig.initIdentityScope(type);

        tagRefDaoConfig = daoConfigMap.get(TagRefDao.class).clone();
        tagRefDaoConfig.initIdentityScope(type);

        taskDaoConfig = daoConfigMap.get(TaskDao.class).clone();
        taskDaoConfig.initIdentityScope(type);

        bookChapterDaoConfig = daoConfigMap.get(BookChapterDao.class).clone();
        bookChapterDaoConfig.initIdentityScope(type);

        bookRecordBeanDaoConfig = daoConfigMap.get(BookRecordBeanDao.class).clone();
        bookRecordBeanDaoConfig.initIdentityScope(type);

        chapterBeanDaoConfig = daoConfigMap.get(ChapterBeanDao.class).clone();
        chapterBeanDaoConfig.initIdentityScope(type);

        downloadTaskBeanDaoConfig = daoConfigMap.get(DownloadTaskBeanDao.class).clone();
        downloadTaskBeanDaoConfig.initIdentityScope(type);

        chapterDao = new ChapterDao(chapterDaoConfig, this);
        comicDao = new ComicDao(comicDaoConfig, this);
        imageUrlDao = new ImageUrlDao(imageUrlDaoConfig, this);
        sourceDao = new SourceDao(sourceDaoConfig, this);
        tagDao = new TagDao(tagDaoConfig, this);
        tagRefDao = new TagRefDao(tagRefDaoConfig, this);
        taskDao = new TaskDao(taskDaoConfig, this);
        bookChapterDao = new BookChapterDao(bookChapterDaoConfig, this);
        bookRecordBeanDao = new BookRecordBeanDao(bookRecordBeanDaoConfig, this);
        chapterBeanDao = new ChapterBeanDao(chapterBeanDaoConfig, this);
        downloadTaskBeanDao = new DownloadTaskBeanDao(downloadTaskBeanDaoConfig, this);

        registerDao(Chapter.class, chapterDao);
        registerDao(Comic.class, comicDao);
        registerDao(ImageUrl.class, imageUrlDao);
        registerDao(Source.class, sourceDao);
        registerDao(Tag.class, tagDao);
        registerDao(TagRef.class, tagRefDao);
        registerDao(Task.class, taskDao);
        registerDao(BookChapter.class, bookChapterDao);
        registerDao(BookRecordBean.class, bookRecordBeanDao);
        registerDao(ChapterBean.class, chapterBeanDao);
        registerDao(DownloadTaskBean.class, downloadTaskBeanDao);
    }
    
    public void clear() {
        chapterDaoConfig.clearIdentityScope();
        comicDaoConfig.clearIdentityScope();
        imageUrlDaoConfig.clearIdentityScope();
        sourceDaoConfig.clearIdentityScope();
        tagDaoConfig.clearIdentityScope();
        tagRefDaoConfig.clearIdentityScope();
        taskDaoConfig.clearIdentityScope();
        bookChapterDaoConfig.clearIdentityScope();
        bookRecordBeanDaoConfig.clearIdentityScope();
        chapterBeanDaoConfig.clearIdentityScope();
        downloadTaskBeanDaoConfig.clearIdentityScope();
    }

    public ChapterDao getChapterDao() {
        return chapterDao;
    }

    public ComicDao getComicDao() {
        return comicDao;
    }

    public ImageUrlDao getImageUrlDao() {
        return imageUrlDao;
    }

    public SourceDao getSourceDao() {
        return sourceDao;
    }

    public TagDao getTagDao() {
        return tagDao;
    }

    public TagRefDao getTagRefDao() {
        return tagRefDao;
    }

    public TaskDao getTaskDao() {
        return taskDao;
    }

    public BookChapterDao getBookChapterDao() {
        return bookChapterDao;
    }

    public BookRecordBeanDao getBookRecordBeanDao() {
        return bookRecordBeanDao;
    }

    public ChapterBeanDao getChapterBeanDao() {
        return chapterBeanDao;
    }

    public DownloadTaskBeanDao getDownloadTaskBeanDao() {
        return downloadTaskBeanDao;
    }

}
