package com.nnmedia.page.model.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.nnmedia.comics.model.ImageUrl.StringConverter;

import com.nnmedia.comics.model.ImageUrl;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "IMAGE_URL".
*/
public class ImageUrlDao extends AbstractDao<ImageUrl, Long> {

    public static final String TABLENAME = "IMAGE_URL";

    /**
     * Properties of entity ImageUrl.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ComicChapter = new Property(1, Long.class, "comicChapter", false, "COMIC_CHAPTER");
        public final static Property Num = new Property(2, int.class, "num", false, "NUM");
        public final static Property Urls = new Property(3, String.class, "urls", false, "URLS");
        public final static Property Chapter = new Property(4, String.class, "chapter", false, "CHAPTER");
        public final static Property State = new Property(5, int.class, "state", false, "STATE");
        public final static Property Height = new Property(6, int.class, "height", false, "HEIGHT");
        public final static Property Width = new Property(7, int.class, "width", false, "WIDTH");
        public final static Property Lazy = new Property(8, boolean.class, "lazy", false, "LAZY");
        public final static Property Loading = new Property(9, boolean.class, "loading", false, "LOADING");
        public final static Property Success = new Property(10, boolean.class, "success", false, "SUCCESS");
        public final static Property Download = new Property(11, boolean.class, "download", false, "DOWNLOAD");
    }

    private final StringConverter urlsConverter = new StringConverter();

    public ImageUrlDao(DaoConfig config) {
        super(config);
    }
    
    public ImageUrlDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"IMAGE_URL\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"COMIC_CHAPTER\" INTEGER NOT NULL ," + // 1: comicChapter
                "\"NUM\" INTEGER NOT NULL ," + // 2: num
                "\"URLS\" TEXT," + // 3: urls
                "\"CHAPTER\" TEXT," + // 4: chapter
                "\"STATE\" INTEGER NOT NULL ," + // 5: state
                "\"HEIGHT\" INTEGER NOT NULL ," + // 6: height
                "\"WIDTH\" INTEGER NOT NULL ," + // 7: width
                "\"LAZY\" INTEGER NOT NULL ," + // 8: lazy
                "\"LOADING\" INTEGER NOT NULL ," + // 9: loading
                "\"SUCCESS\" INTEGER NOT NULL ," + // 10: success
                "\"DOWNLOAD\" INTEGER NOT NULL );"); // 11: download
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"IMAGE_URL\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ImageUrl entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getComicChapter());
        stmt.bindLong(3, entity.getNum());
 
        String[] urls = entity.getUrls();
        if (urls != null) {
            stmt.bindString(4, urlsConverter.convertToDatabaseValue(urls));
        }
 
        String chapter = entity.getChapter();
        if (chapter != null) {
            stmt.bindString(5, chapter);
        }
        stmt.bindLong(6, entity.getState());
        stmt.bindLong(7, entity.getHeight());
        stmt.bindLong(8, entity.getWidth());
        stmt.bindLong(9, entity.getLazy() ? 1L: 0L);
        stmt.bindLong(10, entity.getLoading() ? 1L: 0L);
        stmt.bindLong(11, entity.getSuccess() ? 1L: 0L);
        stmt.bindLong(12, entity.getDownload() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ImageUrl entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getComicChapter());
        stmt.bindLong(3, entity.getNum());
 
        String[] urls = entity.getUrls();
        if (urls != null) {
            stmt.bindString(4, urlsConverter.convertToDatabaseValue(urls));
        }
 
        String chapter = entity.getChapter();
        if (chapter != null) {
            stmt.bindString(5, chapter);
        }
        stmt.bindLong(6, entity.getState());
        stmt.bindLong(7, entity.getHeight());
        stmt.bindLong(8, entity.getWidth());
        stmt.bindLong(9, entity.getLazy() ? 1L: 0L);
        stmt.bindLong(10, entity.getLoading() ? 1L: 0L);
        stmt.bindLong(11, entity.getSuccess() ? 1L: 0L);
        stmt.bindLong(12, entity.getDownload() ? 1L: 0L);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ImageUrl readEntity(Cursor cursor, int offset) {
        ImageUrl entity = new ImageUrl( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // comicChapter
            cursor.getInt(offset + 2), // num
            cursor.isNull(offset + 3) ? null : urlsConverter.convertToEntityProperty(cursor.getString(offset + 3)), // urls
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // chapter
            cursor.getInt(offset + 5), // state
            cursor.getInt(offset + 6), // height
            cursor.getInt(offset + 7), // width
            cursor.getShort(offset + 8) != 0, // lazy
            cursor.getShort(offset + 9) != 0, // loading
            cursor.getShort(offset + 10) != 0, // success
            cursor.getShort(offset + 11) != 0 // download
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ImageUrl entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setComicChapter(cursor.getLong(offset + 1));
        entity.setNum(cursor.getInt(offset + 2));
        entity.setUrls(cursor.isNull(offset + 3) ? null : urlsConverter.convertToEntityProperty(cursor.getString(offset + 3)));
        entity.setChapter(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setState(cursor.getInt(offset + 5));
        entity.setHeight(cursor.getInt(offset + 6));
        entity.setWidth(cursor.getInt(offset + 7));
        entity.setLazy(cursor.getShort(offset + 8) != 0);
        entity.setLoading(cursor.getShort(offset + 9) != 0);
        entity.setSuccess(cursor.getShort(offset + 10) != 0);
        entity.setDownload(cursor.getShort(offset + 11) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ImageUrl entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ImageUrl entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ImageUrl entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
