package com.huli.page.model.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import com.huli.page.model.bean.BookChapter;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import java.util.List;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BOOK_CHAPTER".
*/
public class BookChapterDao extends AbstractDao<BookChapter, String> {

    public static final String TABLENAME = "BOOK_CHAPTER";

    /**
     * Properties of entity BookChapter.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, String.class, "id", true, "ID");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Novel_id = new Property(2, String.class, "novel_id", false, "NOVEL_ID");
        public final static Property Chapter = new Property(3, String.class, "chapter", false, "CHAPTER");
        public final static Property Content_url = new Property(4, String.class, "content_url", false, "CONTENT_URL");
        public final static Property Http_links = new Property(5, String.class, "http_links", false, "HTTP_LINKS");
        public final static Property TaskName = new Property(6, String.class, "taskName", false, "TASK_NAME");
        public final static Property BookId = new Property(7, String.class, "bookId", false, "BOOK_ID");
        public final static Property Start = new Property(8, long.class, "start", false, "START");
        public final static Property End = new Property(9, long.class, "end", false, "END");
    }

    private Query<BookChapter> downloadTaskBean_BookChapterListQuery;
    private Query<BookChapter> bookShelfListBean_BookChapterListQuery;

    public BookChapterDao(DaoConfig config) {
        super(config);
    }
    
    public BookChapterDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BOOK_CHAPTER\" (" + //
                "\"ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: id
                "\"NAME\" TEXT," + // 1: name
                "\"NOVEL_ID\" TEXT," + // 2: novel_id
                "\"CHAPTER\" TEXT," + // 3: chapter
                "\"CONTENT_URL\" TEXT," + // 4: content_url
                "\"HTTP_LINKS\" TEXT," + // 5: http_links
                "\"TASK_NAME\" TEXT," + // 6: taskName
                "\"BOOK_ID\" TEXT," + // 7: bookId
                "\"START\" INTEGER NOT NULL ," + // 8: start
                "\"END\" INTEGER NOT NULL );"); // 9: end
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_BOOK_CHAPTER_BOOK_ID ON \"BOOK_CHAPTER\"" +
                " (\"BOOK_ID\" ASC);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BOOK_CHAPTER\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, BookChapter entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String novel_id = entity.getNovel_id();
        if (novel_id != null) {
            stmt.bindString(3, novel_id);
        }
 
        String chapter = entity.getChapter();
        if (chapter != null) {
            stmt.bindString(4, chapter);
        }
 
        String content_url = entity.getContent_url();
        if (content_url != null) {
            stmt.bindString(5, content_url);
        }
 
        String http_links = entity.getHttp_links();
        if (http_links != null) {
            stmt.bindString(6, http_links);
        }
 
        String taskName = entity.getTaskName();
        if (taskName != null) {
            stmt.bindString(7, taskName);
        }
 
        String bookId = entity.getBookId();
        if (bookId != null) {
            stmt.bindString(8, bookId);
        }
        stmt.bindLong(9, entity.getStart());
        stmt.bindLong(10, entity.getEnd());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, BookChapter entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String novel_id = entity.getNovel_id();
        if (novel_id != null) {
            stmt.bindString(3, novel_id);
        }
 
        String chapter = entity.getChapter();
        if (chapter != null) {
            stmt.bindString(4, chapter);
        }
 
        String content_url = entity.getContent_url();
        if (content_url != null) {
            stmt.bindString(5, content_url);
        }
 
        String http_links = entity.getHttp_links();
        if (http_links != null) {
            stmt.bindString(6, http_links);
        }
 
        String taskName = entity.getTaskName();
        if (taskName != null) {
            stmt.bindString(7, taskName);
        }
 
        String bookId = entity.getBookId();
        if (bookId != null) {
            stmt.bindString(8, bookId);
        }
        stmt.bindLong(9, entity.getStart());
        stmt.bindLong(10, entity.getEnd());
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public BookChapter readEntity(Cursor cursor, int offset) {
        BookChapter entity = new BookChapter( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // novel_id
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // chapter
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // content_url
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // http_links
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // taskName
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // bookId
            cursor.getLong(offset + 8), // start
            cursor.getLong(offset + 9) // end
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, BookChapter entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setNovel_id(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setChapter(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setContent_url(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setHttp_links(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setTaskName(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setBookId(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setStart(cursor.getLong(offset + 8));
        entity.setEnd(cursor.getLong(offset + 9));
     }
    
    @Override
    protected final String updateKeyAfterInsert(BookChapter entity, long rowId) {
        return entity.getId();
    }
    
    @Override
    public String getKey(BookChapter entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(BookChapter entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "bookChapterList" to-many relationship of DownloadTaskBean. */
    public List<BookChapter> _queryDownloadTaskBean_BookChapterList(String taskName) {
        synchronized (this) {
            if (downloadTaskBean_BookChapterListQuery == null) {
                QueryBuilder<BookChapter> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.TaskName.eq(null));
                downloadTaskBean_BookChapterListQuery = queryBuilder.build();
            }
        }
        Query<BookChapter> query = downloadTaskBean_BookChapterListQuery.forCurrentThread();
        query.setParameter(0, taskName);
        return query.list();
    }

    /** Internal query to resolve the "bookChapterList" to-many relationship of BookShelfListBean. */
    public List<BookChapter> _queryBookShelfListBean_BookChapterList(String bookId) {
        synchronized (this) {
            if (bookShelfListBean_BookChapterListQuery == null) {
                QueryBuilder<BookChapter> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.BookId.eq(null));
                bookShelfListBean_BookChapterListQuery = queryBuilder.build();
            }
        }
        Query<BookChapter> query = bookShelfListBean_BookChapterListQuery.forCurrentThread();
        query.setParameter(0, bookId);
        return query.list();
    }

}
