package com.huli.page.model.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.huli.page.model.bean.BookShelfListBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BOOK_SHELF_LIST_BEAN".
*/
public class BookShelfListBeanDao extends AbstractDao<BookShelfListBean, String> {

    public static final String TABLENAME = "BOOK_SHELF_LIST_BEAN";

    /**
     * Properties of entity BookShelfListBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, String.class, "id", true, "ID");
        public final static Property Novel_id = new Property(1, String.class, "novel_id", false, "NOVEL_ID");
        public final static Property User_id = new Property(2, String.class, "user_id", false, "USER_ID");
        public final static Property Novel_name = new Property(3, String.class, "novel_name", false, "NOVEL_NAME");
        public final static Property Novel_image = new Property(4, String.class, "novel_image", false, "NOVEL_IMAGE");
        public final static Property Http_novel_image = new Property(5, String.class, "http_novel_image", false, "HTTP_NOVEL_IMAGE");
        public final static Property Author = new Property(6, String.class, "author", false, "AUTHOR");
        public final static Property Createtime = new Property(7, long.class, "createtime", false, "CREATETIME");
        public final static Property Updatetime = new Property(8, long.class, "updatetime", false, "UPDATETIME");
        public final static Property Deletetime = new Property(9, long.class, "deletetime", false, "DELETETIME");
        public final static Property LastRead = new Property(10, String.class, "lastRead", false, "LAST_READ");
        public final static Property LastChapter = new Property(11, String.class, "lastChapter", false, "LAST_CHAPTER");
        public final static Property IsUpdate = new Property(12, boolean.class, "isUpdate", false, "IS_UPDATE");
        public final static Property IsLocal = new Property(13, boolean.class, "isLocal", false, "IS_LOCAL");
    }

    private DaoSession daoSession;


    public BookShelfListBeanDao(DaoConfig config) {
        super(config);
    }
    
    public BookShelfListBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BOOK_SHELF_LIST_BEAN\" (" + //
                "\"ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: id
                "\"NOVEL_ID\" TEXT," + // 1: novel_id
                "\"USER_ID\" TEXT," + // 2: user_id
                "\"NOVEL_NAME\" TEXT," + // 3: novel_name
                "\"NOVEL_IMAGE\" TEXT," + // 4: novel_image
                "\"HTTP_NOVEL_IMAGE\" TEXT," + // 5: http_novel_image
                "\"AUTHOR\" TEXT," + // 6: author
                "\"CREATETIME\" INTEGER NOT NULL ," + // 7: createtime
                "\"UPDATETIME\" INTEGER NOT NULL ," + // 8: updatetime
                "\"DELETETIME\" INTEGER NOT NULL ," + // 9: deletetime
                "\"LAST_READ\" TEXT," + // 10: lastRead
                "\"LAST_CHAPTER\" TEXT," + // 11: lastChapter
                "\"IS_UPDATE\" INTEGER NOT NULL ," + // 12: isUpdate
                "\"IS_LOCAL\" INTEGER NOT NULL );"); // 13: isLocal
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BOOK_SHELF_LIST_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, BookShelfListBean entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String novel_id = entity.getNovel_id();
        if (novel_id != null) {
            stmt.bindString(2, novel_id);
        }
 
        String user_id = entity.getUser_id();
        if (user_id != null) {
            stmt.bindString(3, user_id);
        }
 
        String novel_name = entity.getNovel_name();
        if (novel_name != null) {
            stmt.bindString(4, novel_name);
        }
 
        String novel_image = entity.getNovel_image();
        if (novel_image != null) {
            stmt.bindString(5, novel_image);
        }
 
        String http_novel_image = entity.getHttp_novel_image();
        if (http_novel_image != null) {
            stmt.bindString(6, http_novel_image);
        }
 
        String author = entity.getAuthor();
        if (author != null) {
            stmt.bindString(7, author);
        }
        stmt.bindLong(8, entity.getCreatetime());
        stmt.bindLong(9, entity.getUpdatetime());
        stmt.bindLong(10, entity.getDeletetime());
 
        String lastRead = entity.getLastRead();
        if (lastRead != null) {
            stmt.bindString(11, lastRead);
        }
 
        String lastChapter = entity.getLastChapter();
        if (lastChapter != null) {
            stmt.bindString(12, lastChapter);
        }
        stmt.bindLong(13, entity.getIsUpdate() ? 1L: 0L);
        stmt.bindLong(14, entity.getIsLocal() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, BookShelfListBean entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String novel_id = entity.getNovel_id();
        if (novel_id != null) {
            stmt.bindString(2, novel_id);
        }
 
        String user_id = entity.getUser_id();
        if (user_id != null) {
            stmt.bindString(3, user_id);
        }
 
        String novel_name = entity.getNovel_name();
        if (novel_name != null) {
            stmt.bindString(4, novel_name);
        }
 
        String novel_image = entity.getNovel_image();
        if (novel_image != null) {
            stmt.bindString(5, novel_image);
        }
 
        String http_novel_image = entity.getHttp_novel_image();
        if (http_novel_image != null) {
            stmt.bindString(6, http_novel_image);
        }
 
        String author = entity.getAuthor();
        if (author != null) {
            stmt.bindString(7, author);
        }
        stmt.bindLong(8, entity.getCreatetime());
        stmt.bindLong(9, entity.getUpdatetime());
        stmt.bindLong(10, entity.getDeletetime());
 
        String lastRead = entity.getLastRead();
        if (lastRead != null) {
            stmt.bindString(11, lastRead);
        }
 
        String lastChapter = entity.getLastChapter();
        if (lastChapter != null) {
            stmt.bindString(12, lastChapter);
        }
        stmt.bindLong(13, entity.getIsUpdate() ? 1L: 0L);
        stmt.bindLong(14, entity.getIsLocal() ? 1L: 0L);
    }

    @Override
    protected final void attachEntity(BookShelfListBean entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public BookShelfListBean readEntity(Cursor cursor, int offset) {
        BookShelfListBean entity = new BookShelfListBean( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // novel_id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // user_id
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // novel_name
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // novel_image
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // http_novel_image
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // author
            cursor.getLong(offset + 7), // createtime
            cursor.getLong(offset + 8), // updatetime
            cursor.getLong(offset + 9), // deletetime
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // lastRead
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // lastChapter
            cursor.getShort(offset + 12) != 0, // isUpdate
            cursor.getShort(offset + 13) != 0 // isLocal
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, BookShelfListBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setNovel_id(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setUser_id(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setNovel_name(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setNovel_image(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setHttp_novel_image(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setAuthor(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setCreatetime(cursor.getLong(offset + 7));
        entity.setUpdatetime(cursor.getLong(offset + 8));
        entity.setDeletetime(cursor.getLong(offset + 9));
        entity.setLastRead(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setLastChapter(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setIsUpdate(cursor.getShort(offset + 12) != 0);
        entity.setIsLocal(cursor.getShort(offset + 13) != 0);
     }
    
    @Override
    protected final String updateKeyAfterInsert(BookShelfListBean entity, long rowId) {
        return entity.getId();
    }
    
    @Override
    public String getKey(BookShelfListBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(BookShelfListBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
