package com.huli.page.model.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.huli.page.model.bean.BookShelfListBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BOOK_SHELF_LIST_BEAN".
*/
public class BookShelfListBeanDao extends AbstractDao<BookShelfListBean, String> {

    public static final String TABLENAME = "BOOK_SHELF_LIST_BEAN";

    /**
     * Properties of entity BookShelfListBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, String.class, "id", true, "ID");
        public final static Property Novel_id = new Property(1, String.class, "novel_id", false, "NOVEL_ID");
        public final static Property User_id = new Property(2, String.class, "user_id", false, "USER_ID");
        public final static Property Novel_name = new Property(3, String.class, "novel_name", false, "NOVEL_NAME");
        public final static Property Novel_image = new Property(4, String.class, "novel_image", false, "NOVEL_IMAGE");
        public final static Property Http_novel_image = new Property(5, String.class, "http_novel_image", false, "HTTP_NOVEL_IMAGE");
        public final static Property Author = new Property(6, String.class, "author", false, "AUTHOR");
        public final static Property Score = new Property(7, float.class, "score", false, "SCORE");
        public final static Property File = new Property(8, String.class, "file", false, "FILE");
        public final static Property Read_sum = new Property(9, int.class, "read_sum", false, "READ_SUM");
        public final static Property Is_end = new Property(10, int.class, "is_end", false, "IS_END");
        public final static Property Type = new Property(11, int.class, "type", false, "TYPE");
        public final static Property Classify_id = new Property(12, int.class, "classify_id", false, "CLASSIFY_ID");
        public final static Property Classify_name = new Property(13, String.class, "classify_name", false, "CLASSIFY_NAME");
        public final static Property Greet = new Property(14, int.class, "greet", false, "GREET");
        public final static Property Word = new Property(15, int.class, "word", false, "WORD");
        public final static Property Is_new = new Property(16, int.class, "is_new", false, "IS_NEW");
        public final static Property Is_hot = new Property(17, int.class, "is_hot", false, "IS_HOT");
        public final static Property Is_copyright = new Property(18, int.class, "is_copyright", false, "IS_COPYRIGHT");
        public final static Property Reading_size = new Property(19, int.class, "reading_size", false, "READING_SIZE");
        public final static Property Introduce = new Property(20, String.class, "introduce", false, "INTRODUCE");
        public final static Property Http_image = new Property(21, String.class, "http_image", false, "HTTP_IMAGE");
        public final static Property Chapter_sum = new Property(22, int.class, "chapter_sum", false, "CHAPTER_SUM");
        public final static Property Is_exist_bookshelf = new Property(23, int.class, "is_exist_bookshelf", false, "IS_EXIST_BOOKSHELF");
        public final static Property Createtime = new Property(24, long.class, "createtime", false, "CREATETIME");
        public final static Property Updatetime = new Property(25, long.class, "updatetime", false, "UPDATETIME");
        public final static Property Deletetime = new Property(26, long.class, "deletetime", false, "DELETETIME");
        public final static Property LastRead = new Property(27, String.class, "lastRead", false, "LAST_READ");
        public final static Property LastChapter = new Property(28, String.class, "lastChapter", false, "LAST_CHAPTER");
        public final static Property IsUpdate = new Property(29, boolean.class, "isUpdate", false, "IS_UPDATE");
        public final static Property IsLocal = new Property(30, boolean.class, "isLocal", false, "IS_LOCAL");
    }

    private DaoSession daoSession;


    public BookShelfListBeanDao(DaoConfig config) {
        super(config);
    }
    
    public BookShelfListBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BOOK_SHELF_LIST_BEAN\" (" + //
                "\"ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: id
                "\"NOVEL_ID\" TEXT," + // 1: novel_id
                "\"USER_ID\" TEXT," + // 2: user_id
                "\"NOVEL_NAME\" TEXT," + // 3: novel_name
                "\"NOVEL_IMAGE\" TEXT," + // 4: novel_image
                "\"HTTP_NOVEL_IMAGE\" TEXT," + // 5: http_novel_image
                "\"AUTHOR\" TEXT," + // 6: author
                "\"SCORE\" REAL NOT NULL ," + // 7: score
                "\"FILE\" TEXT," + // 8: file
                "\"READ_SUM\" INTEGER NOT NULL ," + // 9: read_sum
                "\"IS_END\" INTEGER NOT NULL ," + // 10: is_end
                "\"TYPE\" INTEGER NOT NULL ," + // 11: type
                "\"CLASSIFY_ID\" INTEGER NOT NULL ," + // 12: classify_id
                "\"CLASSIFY_NAME\" TEXT," + // 13: classify_name
                "\"GREET\" INTEGER NOT NULL ," + // 14: greet
                "\"WORD\" INTEGER NOT NULL ," + // 15: word
                "\"IS_NEW\" INTEGER NOT NULL ," + // 16: is_new
                "\"IS_HOT\" INTEGER NOT NULL ," + // 17: is_hot
                "\"IS_COPYRIGHT\" INTEGER NOT NULL ," + // 18: is_copyright
                "\"READING_SIZE\" INTEGER NOT NULL ," + // 19: reading_size
                "\"INTRODUCE\" TEXT," + // 20: introduce
                "\"HTTP_IMAGE\" TEXT," + // 21: http_image
                "\"CHAPTER_SUM\" INTEGER NOT NULL ," + // 22: chapter_sum
                "\"IS_EXIST_BOOKSHELF\" INTEGER NOT NULL ," + // 23: is_exist_bookshelf
                "\"CREATETIME\" INTEGER NOT NULL ," + // 24: createtime
                "\"UPDATETIME\" INTEGER NOT NULL ," + // 25: updatetime
                "\"DELETETIME\" INTEGER NOT NULL ," + // 26: deletetime
                "\"LAST_READ\" TEXT," + // 27: lastRead
                "\"LAST_CHAPTER\" TEXT," + // 28: lastChapter
                "\"IS_UPDATE\" INTEGER NOT NULL ," + // 29: isUpdate
                "\"IS_LOCAL\" INTEGER NOT NULL );"); // 30: isLocal
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BOOK_SHELF_LIST_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, BookShelfListBean entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String novel_id = entity.getNovel_id();
        if (novel_id != null) {
            stmt.bindString(2, novel_id);
        }
 
        String user_id = entity.getUser_id();
        if (user_id != null) {
            stmt.bindString(3, user_id);
        }
 
        String novel_name = entity.getNovel_name();
        if (novel_name != null) {
            stmt.bindString(4, novel_name);
        }
 
        String novel_image = entity.getNovel_image();
        if (novel_image != null) {
            stmt.bindString(5, novel_image);
        }
 
        String http_novel_image = entity.getHttp_novel_image();
        if (http_novel_image != null) {
            stmt.bindString(6, http_novel_image);
        }
 
        String author = entity.getAuthor();
        if (author != null) {
            stmt.bindString(7, author);
        }
        stmt.bindDouble(8, entity.getScore());
 
        String file = entity.getFile();
        if (file != null) {
            stmt.bindString(9, file);
        }
        stmt.bindLong(10, entity.getRead_sum());
        stmt.bindLong(11, entity.getIs_end());
        stmt.bindLong(12, entity.getType());
        stmt.bindLong(13, entity.getClassify_id());
 
        String classify_name = entity.getClassify_name();
        if (classify_name != null) {
            stmt.bindString(14, classify_name);
        }
        stmt.bindLong(15, entity.getGreet());
        stmt.bindLong(16, entity.getWord());
        stmt.bindLong(17, entity.getIs_new());
        stmt.bindLong(18, entity.getIs_hot());
        stmt.bindLong(19, entity.getIs_copyright());
        stmt.bindLong(20, entity.getReading_size());
 
        String introduce = entity.getIntroduce();
        if (introduce != null) {
            stmt.bindString(21, introduce);
        }
 
        String http_image = entity.getHttp_image();
        if (http_image != null) {
            stmt.bindString(22, http_image);
        }
        stmt.bindLong(23, entity.getChapter_sum());
        stmt.bindLong(24, entity.getIs_exist_bookshelf());
        stmt.bindLong(25, entity.getCreatetime());
        stmt.bindLong(26, entity.getUpdatetime());
        stmt.bindLong(27, entity.getDeletetime());
 
        String lastRead = entity.getLastRead();
        if (lastRead != null) {
            stmt.bindString(28, lastRead);
        }
 
        String lastChapter = entity.getLastChapter();
        if (lastChapter != null) {
            stmt.bindString(29, lastChapter);
        }
        stmt.bindLong(30, entity.getIsUpdate() ? 1L: 0L);
        stmt.bindLong(31, entity.getIsLocal() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, BookShelfListBean entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String novel_id = entity.getNovel_id();
        if (novel_id != null) {
            stmt.bindString(2, novel_id);
        }
 
        String user_id = entity.getUser_id();
        if (user_id != null) {
            stmt.bindString(3, user_id);
        }
 
        String novel_name = entity.getNovel_name();
        if (novel_name != null) {
            stmt.bindString(4, novel_name);
        }
 
        String novel_image = entity.getNovel_image();
        if (novel_image != null) {
            stmt.bindString(5, novel_image);
        }
 
        String http_novel_image = entity.getHttp_novel_image();
        if (http_novel_image != null) {
            stmt.bindString(6, http_novel_image);
        }
 
        String author = entity.getAuthor();
        if (author != null) {
            stmt.bindString(7, author);
        }
        stmt.bindDouble(8, entity.getScore());
 
        String file = entity.getFile();
        if (file != null) {
            stmt.bindString(9, file);
        }
        stmt.bindLong(10, entity.getRead_sum());
        stmt.bindLong(11, entity.getIs_end());
        stmt.bindLong(12, entity.getType());
        stmt.bindLong(13, entity.getClassify_id());
 
        String classify_name = entity.getClassify_name();
        if (classify_name != null) {
            stmt.bindString(14, classify_name);
        }
        stmt.bindLong(15, entity.getGreet());
        stmt.bindLong(16, entity.getWord());
        stmt.bindLong(17, entity.getIs_new());
        stmt.bindLong(18, entity.getIs_hot());
        stmt.bindLong(19, entity.getIs_copyright());
        stmt.bindLong(20, entity.getReading_size());
 
        String introduce = entity.getIntroduce();
        if (introduce != null) {
            stmt.bindString(21, introduce);
        }
 
        String http_image = entity.getHttp_image();
        if (http_image != null) {
            stmt.bindString(22, http_image);
        }
        stmt.bindLong(23, entity.getChapter_sum());
        stmt.bindLong(24, entity.getIs_exist_bookshelf());
        stmt.bindLong(25, entity.getCreatetime());
        stmt.bindLong(26, entity.getUpdatetime());
        stmt.bindLong(27, entity.getDeletetime());
 
        String lastRead = entity.getLastRead();
        if (lastRead != null) {
            stmt.bindString(28, lastRead);
        }
 
        String lastChapter = entity.getLastChapter();
        if (lastChapter != null) {
            stmt.bindString(29, lastChapter);
        }
        stmt.bindLong(30, entity.getIsUpdate() ? 1L: 0L);
        stmt.bindLong(31, entity.getIsLocal() ? 1L: 0L);
    }

    @Override
    protected final void attachEntity(BookShelfListBean entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public BookShelfListBean readEntity(Cursor cursor, int offset) {
        BookShelfListBean entity = new BookShelfListBean( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // novel_id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // user_id
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // novel_name
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // novel_image
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // http_novel_image
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // author
            cursor.getFloat(offset + 7), // score
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // file
            cursor.getInt(offset + 9), // read_sum
            cursor.getInt(offset + 10), // is_end
            cursor.getInt(offset + 11), // type
            cursor.getInt(offset + 12), // classify_id
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // classify_name
            cursor.getInt(offset + 14), // greet
            cursor.getInt(offset + 15), // word
            cursor.getInt(offset + 16), // is_new
            cursor.getInt(offset + 17), // is_hot
            cursor.getInt(offset + 18), // is_copyright
            cursor.getInt(offset + 19), // reading_size
            cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20), // introduce
            cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21), // http_image
            cursor.getInt(offset + 22), // chapter_sum
            cursor.getInt(offset + 23), // is_exist_bookshelf
            cursor.getLong(offset + 24), // createtime
            cursor.getLong(offset + 25), // updatetime
            cursor.getLong(offset + 26), // deletetime
            cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27), // lastRead
            cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28), // lastChapter
            cursor.getShort(offset + 29) != 0, // isUpdate
            cursor.getShort(offset + 30) != 0 // isLocal
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, BookShelfListBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setNovel_id(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setUser_id(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setNovel_name(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setNovel_image(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setHttp_novel_image(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setAuthor(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setScore(cursor.getFloat(offset + 7));
        entity.setFile(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setRead_sum(cursor.getInt(offset + 9));
        entity.setIs_end(cursor.getInt(offset + 10));
        entity.setType(cursor.getInt(offset + 11));
        entity.setClassify_id(cursor.getInt(offset + 12));
        entity.setClassify_name(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setGreet(cursor.getInt(offset + 14));
        entity.setWord(cursor.getInt(offset + 15));
        entity.setIs_new(cursor.getInt(offset + 16));
        entity.setIs_hot(cursor.getInt(offset + 17));
        entity.setIs_copyright(cursor.getInt(offset + 18));
        entity.setReading_size(cursor.getInt(offset + 19));
        entity.setIntroduce(cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20));
        entity.setHttp_image(cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21));
        entity.setChapter_sum(cursor.getInt(offset + 22));
        entity.setIs_exist_bookshelf(cursor.getInt(offset + 23));
        entity.setCreatetime(cursor.getLong(offset + 24));
        entity.setUpdatetime(cursor.getLong(offset + 25));
        entity.setDeletetime(cursor.getLong(offset + 26));
        entity.setLastRead(cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27));
        entity.setLastChapter(cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28));
        entity.setIsUpdate(cursor.getShort(offset + 29) != 0);
        entity.setIsLocal(cursor.getShort(offset + 30) != 0);
     }
    
    @Override
    protected final String updateKeyAfterInsert(BookShelfListBean entity, long rowId) {
        return entity.getId();
    }
    
    @Override
    public String getKey(BookShelfListBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(BookShelfListBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
