package com.huli.page.model.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.huli.page.model.bean.ChapterBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CHAPTER_BEAN".
*/
public class ChapterBeanDao extends AbstractDao<ChapterBean, String> {

    public static final String TABLENAME = "CHAPTER_BEAN";

    /**
     * Properties of entity ChapterBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, String.class, "id", true, "ID");
        public final static Property Content = new Property(1, String.class, "content", false, "CONTENT");
        public final static Property Links = new Property(2, String.class, "links", false, "LINKS");
        public final static Property Name = new Property(3, String.class, "name", false, "NAME");
        public final static Property Novel_id = new Property(4, String.class, "novel_id", false, "NOVEL_ID");
        public final static Property Chapter = new Property(5, int.class, "chapter", false, "CHAPTER");
        public final static Property Content_url = new Property(6, String.class, "content_url", false, "CONTENT_URL");
        public final static Property Http_links = new Property(7, String.class, "http_links", false, "HTTP_LINKS");
    }


    public ChapterBeanDao(DaoConfig config) {
        super(config);
    }
    
    public ChapterBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CHAPTER_BEAN\" (" + //
                "\"ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: id
                "\"CONTENT\" TEXT," + // 1: content
                "\"LINKS\" TEXT," + // 2: links
                "\"NAME\" TEXT," + // 3: name
                "\"NOVEL_ID\" TEXT," + // 4: novel_id
                "\"CHAPTER\" INTEGER NOT NULL ," + // 5: chapter
                "\"CONTENT_URL\" TEXT," + // 6: content_url
                "\"HTTP_LINKS\" TEXT);"); // 7: http_links
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CHAPTER_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ChapterBean entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(2, content);
        }
 
        String links = entity.getLinks();
        if (links != null) {
            stmt.bindString(3, links);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(4, name);
        }
 
        String novel_id = entity.getNovel_id();
        if (novel_id != null) {
            stmt.bindString(5, novel_id);
        }
        stmt.bindLong(6, entity.getChapter());
 
        String content_url = entity.getContent_url();
        if (content_url != null) {
            stmt.bindString(7, content_url);
        }
 
        String http_links = entity.getHttp_links();
        if (http_links != null) {
            stmt.bindString(8, http_links);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ChapterBean entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(2, content);
        }
 
        String links = entity.getLinks();
        if (links != null) {
            stmt.bindString(3, links);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(4, name);
        }
 
        String novel_id = entity.getNovel_id();
        if (novel_id != null) {
            stmt.bindString(5, novel_id);
        }
        stmt.bindLong(6, entity.getChapter());
 
        String content_url = entity.getContent_url();
        if (content_url != null) {
            stmt.bindString(7, content_url);
        }
 
        String http_links = entity.getHttp_links();
        if (http_links != null) {
            stmt.bindString(8, http_links);
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public ChapterBean readEntity(Cursor cursor, int offset) {
        ChapterBean entity = new ChapterBean( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // content
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // links
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // name
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // novel_id
            cursor.getInt(offset + 5), // chapter
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // content_url
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7) // http_links
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ChapterBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setContent(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setLinks(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setNovel_id(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setChapter(cursor.getInt(offset + 5));
        entity.setContent_url(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setHttp_links(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
     }
    
    @Override
    protected final String updateKeyAfterInsert(ChapterBean entity, long rowId) {
        return entity.getId();
    }
    
    @Override
    public String getKey(ChapterBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ChapterBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
