package com.huli.page.model.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.huli.page.model.bean.BookChapter;
import com.huli.page.model.bean.DownloadTaskBean;
import com.huli.page.model.bean.BookShelfListBean;
import com.huli.page.model.bean.BookRecordBean;
import com.huli.page.model.bean.ChapterBean;

import com.huli.page.model.dao.BookChapterDao;
import com.huli.page.model.dao.DownloadTaskBeanDao;
import com.huli.page.model.dao.BookShelfListBeanDao;
import com.huli.page.model.dao.BookRecordBeanDao;
import com.huli.page.model.dao.ChapterBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bookChapterDaoConfig;
    private final DaoConfig downloadTaskBeanDaoConfig;
    private final DaoConfig bookShelfListBeanDaoConfig;
    private final DaoConfig bookRecordBeanDaoConfig;
    private final DaoConfig chapterBeanDaoConfig;

    private final BookChapterDao bookChapterDao;
    private final DownloadTaskBeanDao downloadTaskBeanDao;
    private final BookShelfListBeanDao bookShelfListBeanDao;
    private final BookRecordBeanDao bookRecordBeanDao;
    private final ChapterBeanDao chapterBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bookChapterDaoConfig = daoConfigMap.get(BookChapterDao.class).clone();
        bookChapterDaoConfig.initIdentityScope(type);

        downloadTaskBeanDaoConfig = daoConfigMap.get(DownloadTaskBeanDao.class).clone();
        downloadTaskBeanDaoConfig.initIdentityScope(type);

        bookShelfListBeanDaoConfig = daoConfigMap.get(BookShelfListBeanDao.class).clone();
        bookShelfListBeanDaoConfig.initIdentityScope(type);

        bookRecordBeanDaoConfig = daoConfigMap.get(BookRecordBeanDao.class).clone();
        bookRecordBeanDaoConfig.initIdentityScope(type);

        chapterBeanDaoConfig = daoConfigMap.get(ChapterBeanDao.class).clone();
        chapterBeanDaoConfig.initIdentityScope(type);

        bookChapterDao = new BookChapterDao(bookChapterDaoConfig, this);
        downloadTaskBeanDao = new DownloadTaskBeanDao(downloadTaskBeanDaoConfig, this);
        bookShelfListBeanDao = new BookShelfListBeanDao(bookShelfListBeanDaoConfig, this);
        bookRecordBeanDao = new BookRecordBeanDao(bookRecordBeanDaoConfig, this);
        chapterBeanDao = new ChapterBeanDao(chapterBeanDaoConfig, this);

        registerDao(BookChapter.class, bookChapterDao);
        registerDao(DownloadTaskBean.class, downloadTaskBeanDao);
        registerDao(BookShelfListBean.class, bookShelfListBeanDao);
        registerDao(BookRecordBean.class, bookRecordBeanDao);
        registerDao(ChapterBean.class, chapterBeanDao);
    }
    
    public void clear() {
        bookChapterDaoConfig.clearIdentityScope();
        downloadTaskBeanDaoConfig.clearIdentityScope();
        bookShelfListBeanDaoConfig.clearIdentityScope();
        bookRecordBeanDaoConfig.clearIdentityScope();
        chapterBeanDaoConfig.clearIdentityScope();
    }

    public BookChapterDao getBookChapterDao() {
        return bookChapterDao;
    }

    public DownloadTaskBeanDao getDownloadTaskBeanDao() {
        return downloadTaskBeanDao;
    }

    public BookShelfListBeanDao getBookShelfListBeanDao() {
        return bookShelfListBeanDao;
    }

    public BookRecordBeanDao getBookRecordBeanDao() {
        return bookRecordBeanDao;
    }

    public ChapterBeanDao getChapterBeanDao() {
        return chapterBeanDao;
    }

}
